export const PRODUCT_ADD = "PRODUCT_ADD"
export const PRODUCT_REMOVE = "PRODUCT_REMOVE"
export const PRODUCT_EMPTY = "PRODUCT_EMPRT"
export const PRODUCT_SET = "PRODUCT_SET"
export const PRODUCT_LIST = 'PRODUCT_LIST'